[project]
name = "llm-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.6.0",
    "openai>=1.73.0",
    "pip>=25.0.1",
    "pytest>=8.3.5",
]
